### ISSUE TITLE
It is not working any more

### ISSUE THREAD

**Issue by hyspace** [superkam/Alfred2_EuDic_Search#1]
I tried with Eudic 3.1.4 and it is not working.

My eudic located in `/Applications/Eudic`, maybe the name of the program is wrong?

I tried to open the workflow file but it seems that it is not a readable file. So could you provide some information about the script?

**Comment by superkam** [comment]
Try to change string "open /Applications/欧路词典.app" to "open /Applications/EuDic.app". 
EuDic doesn't support AppleScript so I can only do this by simulating key pressing, not a perfect solution but it works so far.

**Comment by achillesliu** [comment]
For people that is using lite version from Mac App Store, one more change has to be done in the line,
    tell process "EuDic"   --> tell process "EuDic Free".
And also the above modification should be also changed to "EuDic_en_Free.app", too.
